package com.bbd_coffee_app.BBD_Coffee_Application.controller;

import com.bbd_coffee_app.BBD_Coffee_Application.model.Office;
import com.bbd_coffee_app.BBD_Coffee_Application.service.OfficeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import com.bbd_coffee_app.BBD_Coffee_Application.DTO.OfficeDTO;

import java.util.List;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/office")
public class OfficeController {

    @Autowired
    private OfficeService officeService;

    @PostMapping
    public ResponseEntity<Void> createOffice(@RequestBody Office office) {
        try {
            // The ID will be auto-generated by the database
            Office createdOffice = officeService.createOffice(office);
            return new ResponseEntity<>(HttpStatus.CREATED);
        } catch (Exception e) {
            return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }

    @GetMapping
    public ResponseEntity<List<OfficeDTO>> getAllOffice() {
        try {
            List<Office> offices = officeService.getAllOffice();
            List<OfficeDTO> officeDTOs = offices.stream()
                    .sorted((o1, o2) -> Integer.compare(o1.getOfficeID(), o2.getOfficeID()))
                    .map(office -> {
                        OfficeDTO dto = new OfficeDTO();
                        dto.setOfficeID(office.getOfficeID());
                        dto.setOfficeName(office.getOfficeName());
                        return dto;
                    }).collect(Collectors.toList());

            return new ResponseEntity<>(officeDTOs, HttpStatus.OK);
        } catch (Exception e) {
            return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }
}
