
package com.bbd_coffee_app.BBD_Coffee_Application.controller;

import com.bbd_coffee_app.BBD_Coffee_Application.dto.OfficeDTO;
import com.bbd_coffee_app.BBD_Coffee_Application.model.Office;
import com.bbd_coffee_app.BBD_Coffee_Application.service.OfficeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/office")
public class OfficeController {
    @Autowired
    private OfficeService officeService;

    @PostMapping
    public ResponseEntity<String> createOffice(@RequestBody Office office) {
        try {
            // The ID will be auto-generated by the database
            Office createdOffice = officeService.createOffice(office);
            return new ResponseEntity<>("Office created successfully with ID: " + createdOffice.getOfficeID(), HttpStatus.CREATED);
        } catch (Exception e) {
            return new ResponseEntity<>("Error creating office: " + e.getMessage(), HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }
}